# Site settings
title: Ironic Blog
email: nercury@gmail.com
description: >
  Articles and tutorials about Rust, Embedded development and Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nercury.github.io" # the base hostname & protocol for your site
twitter_username: nercury
github_username:  Nercury
github: [metadata]

# Build settings
# markdown: redcarpet
# highlighter: pygments

redcarpet:
    extensions:    ["with_toc_data"]
